### ISSUE TITLE
Adding run on startup option

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#54]
I am using TB myself and what I personally did is that I wrote a script in c that runs TB on startup once in everyday so I can simply write something for the day.

What if we got this option built in to the TB ?

**Comment by emvigo** [comment]
Interesting. Would you mind to post your script here as to see what it does and how? The standard thing in Linux-based OSs nowadays would be to provide a systemd unit, though.

**Comment by mahditakrim** [comment]
You'r right about systemd unit but as a quick resulting method I combined my script with a program called StartupApplication which runs the script on startup.
I will try with systemd unit later.

Would you like to see the script now ?

**Comment by emvigo** [comment]
Yeah, I'd like to see it, to get a grasp of what the feature is meant to be like. If it's too long, paste it on gist.github.com!

**Comment by mahditakrim** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>

int exists(const char *fname)
{
    FILE *file;
    if ((file = fopen(fname, "r")))
    {
        fclose(file);
        return 1;
    }
    return 0;
}

int main()
{
    const char *wtr = "/home/mahdi/Programs/TB/turbodiaryRS/wtr.ini",
     *command = "cd && konsole -e './Programs/TB/turbodiary/turbodiary -w'";
    FILE *f;
    time_t current_time = time(NULL);
    struct tm *now = localtime(&current_time);

    if(exists(wtr) == 0)
    {
        f = fopen(wtr, "w");
        fprintf(f, "%d", now->tm_mday);
        fclose(f);
        system(command);
        return 0;
    }

    f = fopen(wtr, "r");
    char read[2], mday[2], ch;
    for(int i=0; (ch = fgetc(f)) != EOF; i++) 
    {
        read[i] = ch;
        read[i+1] = '\0';        
    }
    fclose(f);

    sprintf(mday, "%d", now->tm_mday);
    if(strcmp(read, mday) != 0)
    {
        f = fopen(wtr, "w");
        fprintf(f, "%d", now->tm_mday);
        fclose(f);
        system(command);
    }
}

**Comment by emvigo** [comment]
Hm, I've got a couple of problems with this idea and this implementation.

First of all, this requires KDE Apps as a dependency, because of Konsole. Second, it's hardcoded to work with a non-protected diary. In general, using C for this kind of things is suboptimal at the very least: a bash script would be much better.

On the other hand, the idea of having Turbo Diary being opened at startup, while it's nice, would require some heavy reworking of how the interface works, in order to have a sane setup. I myself have played in the past around the idea of having TD show up a random entry at startup.

A systemd unit would obviously be the most-supported DE-agnostic way to do this, but we still would need to know whether we're in a tty, an ssh-session, or a regular DE (for which a simple GUI dialog or a GNOME extension/Plasma applet would actually better than firing up a terminal emulator). From a past project, detecting those things is *very* hard and not always works.

I'll close this issue and tag it as "wontfix." It's not that I'm against the idea, but we need Turbo Diary be less terminal-centric in order to have a good base to implement something like this. Thanks for your contribution!

**Comment by mahditakrim** [comment]
I use konsole because i write diary in persian.
That was just an idea, take it easy!

**Comment by emvigo** [comment]
I'm Latin American; we sometimes sound a bit harsh in English sometimes because of how we 'translate' things from Spanish. Excuse me if it sounded too harsh.
