### ISSUE TITLE
Max character limitation warning

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#55]
It's good to have a character counter showing the number of characters that user has entered and letting the user know if it's gone over max size.

**Comment by emvigo** [comment]
There have past attempts to give Turbo Diary an ncurses-based UI. That would allow having a "live counter" (like Twitter's). Doing this only using standard I/O routines is technically impossible: we need to go one step down in the abstraction layer and do terminal character-cell manipulation (termios/termcap/ncurses) and even intercept keystrokes ourselves in so-called 'raw' mode. The problem is that doing this right implies implementing half a nano-like text editor and at least I haven't been able to come up with code that is nearly usable for that.

Any ideas on how to advance this further?

**Comment by mahditakrim** [comment]
I think it should be really cool if TB make sound or some kind of alarm that can announce user to know that it's done by character.

Honestly I found it really annoying writing diary then knowing it's not fully saved :face_with_head_bandage:

**Comment by emvigo** [comment]
Maybe a quick hackish provisional solution would be to warn the user that the input entered is longer than the max. size and then if so, give them the ability to try again? Not ideal so far, but at least it'd address the scenario you're talking about (yes, it's quite annoying; it's probably the thing I hate most when using Turbo Diary lol).

**Comment by mahditakrim** [comment]
So, may I work on it?

**Comment by emvigo** [comment]
Of course! :D
