### ISSUE TITLE
Changing title behavior

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#67]
After a while using TD I found out that most of the time I don't enter a title for the diary and it's really annoying to enter the diary text into the title then know that it was title :angry: 

So how about to manage an option to handle this in TD to make it less annoying ?

**Comment by emvigo** [comment]
Having optional titles requires fine-tuning the file format so that it doesn't break. It's feasible, but it requires some engineering at the parser. Let's think about it!

**Comment by mahditakrim** [comment]
Hi, I'm back

What I mean is, when the first time the user is creating .tdf file, TD should ask for another option, whether to have title for each diary entry or not.

Does it require changing the file format or something like that ?

**Comment by emvigo** [comment]
I think this would require storing that information somewhere on the file so that the first field in the TSV-formatted data is never written nor read.  That could lead to breaking backwards compatibility; I don't care about breaking it at this 0.x stage, but it's something that must be factored in.

As the proposal stands right now, I think it's a bit overkill: titles are already optional. However, your idea shows that the current file format should be made more flexible and future-proof. I'm closing this issue with `wontfix', but I'm pretty sure that the file format needs to be reworked.

**Comment by mahditakrim** [comment]
Alright.
