### ISSUE TITLE
Feeling and mood status 

### ISSUE THREAD

**Issue by mahditakrim** [emvigo/turbodiary#70]
We have two part in diary sections, Title and diary text.
So how about to have another part, in which you can put your mood and feeling of the day and you can see in the future that what was your feeling when you were writing the diary.
It is obvious that this should be optional like the Title part.

The important question is, does it require to change the file format ?

**Comment by emvigo** [comment]
I like this! Should this be a closed list of options or an open field (like titles are)? For some reason I prefer it to be a closed list of options, but what have you in mind?

Yes, this requires changing the format of course and may render past journals incompatible with a new version of Turbo Diary that adopts this (but everyone should be aware that kind of things happens in any 0.x version of any software... I'm against guaranteeing any backwards compatibility until we hit 1.0).

**Comment by mahditakrim** [comment]
Happy you like this,
Well, what do you mean by closed list of options?, you mean some kind of lists like below:
1. Happy :smile: 
2. Angry :angry: 
3. lovely :heart:

What I have in mind is a combination of both also with emojis for better explanation of the feeling, 
but still optional like Title.

For the file format changing, as a person who is already using TD, I think it can be a good idea to somehow give awareness to the user so she/he can get backup from the old files.
I know it's too early but let's think about it.

**Comment by emvigo** [comment]
Emojis require solving #57, because they need proper UTF-8 support. Also be aware that many terminal clients won't be able to show them properly.

Having a 'list' of emotions could be more interesting than having yet another open field (e.g. the title) for the user to write into. What I'm not sure is how to display that on screen without getting into a whole ncurses/termcap-based UI just because we want a menu of sorts for this single feature. If you've got some draft code, that'd be helpful.

> For the file format changing, as a person who is already using TD, I think it can be a good idea to somehow give awareness to the user so she/he can get backup from the old files.
I know it's too early but let's think about it.

You're actively using a software that straightout tells you in its README that you shouldn't be using it in production. Things are supposed to break at any point. The warning is already there.

**Comment by mahditakrim** [comment]
What I have in my mind is when user entered Title the next part is the Mood section in which we show a list of typical moods and emotions with numbers alongside them, then the user can choose one, two or maybe three of them (for complex feelings) by entering the number of them in a specific format, and also remember we showed typical ones so we can show the whole list to the user by typing 
'turbodiary --list-of-moods' or something like that in another terminal.

**Comment by emvigo** [comment]
OK, I sort of see the idea you have in mind. The challenge here is how to present this in a way that doesn't clutter the UI. The "backend" implementation wouldn't be any harder than adding some kind of enum type into tdentry... Then there's the parser, which should get adjusted and there's where incompatibilities *will* arise.
Do you feel confident to tackle this code by yourself?

**Comment by mahditakrim** [comment]
I think for this particular issue I have to understand the whole project's code very well.
I feel confident to give it a try. :hammer:

**Comment by mahditakrim** [comment]
@RibalGZ ,
What is so funny ?!

**Comment by mahditakrim** [comment]
@emvigo ,
why did you set another variable from 'filesize' ?
What is the usage, is it redundant ?

Address -> td.c line 754

**Comment by emvigo** [comment]
> @emvigo ,
> why did you set another variable from 'filesize' ?
> What is the usage, is it redundant ?
> 
> Address -> td.c line 754

Thanks for catching that one. I guess it was a leftover from some previous code or who knows. I removed tdstr_size from that block of code and pushed the changes to master.

**Comment by mahditakrim** [comment]
@emvigo ,
Why do you make a linked list out of .tdf file then for example add a new record to it and then save the whole linked list to the file ?!!!

Why don't you simply add the new diary record to the file directly ?

**Comment by emvigo** [comment]
> @emvigo ,
> Why do you make a linked list out of .tdf file then for example add a new record to it and then save the whole linked list to the file ?!!!
> 
> Why don't you simply add the new diary record to the file directly ?

Because of OpenSSL. Everything must be ready in memory before dumping it into the file because the cipher works on the whole file as a unit. Of course for diaries that aren't encrypted that's not necessary, but this way we have just one data structure to cover both scenarios.

**Comment by mahditakrim** [comment]
I know having one data structure for both scenarios works well, but this way the code is so complex for a very first step program and also this will wast lots of memory and will increase memory handling bugs in the future.
So I think it's better to separate the crypto mode's development from typical mode as soon as possible.
And how about to passing diaries line by line to the cipher then adding to the file, is it possible ?

**Comment by emvigo** [comment]
> I know having one data structure for both scenarios works well, but this way the code is so complex for a very first step program and also this will wast lots of memory and will increase memory handling bugs in the future.
> So I think it's better to separate the crypto mode's development from typical mode as soon as possible.

This is not the place to discuss the overall architecture of the project. Here we are to discuss a very specific feature you've proposed. If you want to discuss the architecture, I encourage you to send a pull request with your idea. In any case, I don't like discussing things so long without seeing any line of code. I can help you if you need it, but I need you to show some code first in order to know what your thoughts are. Programming is about writing down ideas in code.

In general, I'll ignore any further comment here that doesn't relate to the specific feature originally proposed. I'll be testing some code these days related to this.

> And how about to passing diaries line by line to the cipher then adding to the file, is it possible ?

Not the place to discuss this, but nonetheless: please take a look at the OpenSSL API and, in general, how AES (and any modern cipher) works. Modern ciphers need to know the whole "block" of data beforehand to be able to handle it. You just can't append data sequentially: it corrupts the ciphertext beyond recovery. That's why we need to do everything in memory.

**Comment by mahditakrim** [comment]
@emvigo ,
I can't figure out what is going on with the tabs in .tdf file records and I'm not able to upload screenshot or any file to show the issue to you so i'm gonna try to send a screenshot via email.

In case I could't send it please try it yourself, enter a diary whom title is less than 8 digits and then see the .tdf file's content.

(I'm in the reviewing process, so there is no code yet)

**Comment by emvigo** [comment]
Got your email. Looks like a representation problem. You know, programs represent tabs as they like. As long as we read them as \t we're fine (and the fact that PCRE2 isn't complaining is a good sign).

**Comment by mahditakrim** [comment]
Records with less than 8 digit title are acting like there is no tab between title and diary text.
So you mean there is no worries for that and we can proceed developing ?

**Comment by emvigo** [comment]
When examining data in a development setting, aleays check your files using hexdump. You should see '\t' as 0x09. Look at the output below. 

```
$ hexdump -C ~/.turbodiary/default.tdf
00000000  70 6c 09 31 32 30 30 0a  32 30 32 30 30 33 30 31  |pl.1200.20200301|
00000010  09 61 62 63 64 09 68 65  6c 6c 6f 0a 32 30 32 30  |.abcd.hello.2020|
00000020  30 33 30 31 09 61 62 63  64 65 66 67 68 69 6a 6b  |0301.abcdefghijk|
00000030  6c 6d 6e 6f 70 09 54 68  65 20 74 69 74 6c 65 20  |lmnop.The title |
00000040  69 73 20 6d 6f 72 65 20  74 68 61 6e 20 38 20 63  |is more than 8 c|
00000050  68 61 72 73 20 6c 6f 6e  67 0a                    |hars long.|
0000005a
```

Never trust any editor, because they're free to show tabs with the width they like. The important thing here is to have a separator.

**Comment by mahditakrim** [comment]
@emvigo ,
One silly question:
is it possible to use a string (char *) variable for encryption process instead of linked list?
(as you said the whole diary object should be ready in memory before encryption)

**Comment by mahditakrim** [comment]
@emvigo ,
Timestamp length seems like is always 9 characters, so may I change the code and just add 9 characters to 'tdentry_str_size' ?

Address -> td.c line 105

**Comment by emvigo** [comment]
> @emvigo ,
> One silly question:
> is it possible to use a string (char *) variable for encryption process instead of linked list?
> (as you said the whole diary object should be ready in memory before encryption)

That's already what the code does. Take a look at tdobj_to_string and tdobj_from_string: they're almost the first thing tdobj_to_file and tdobj_from_file call. The linked list is serialized into a string because OpenSSL only operates on strings... as well as all standard I/O functions do. We must do this intermediate step to get everything working.

**Comment by emvigo** [comment]
> @emvigo ,
> Timestamp length seems like is always 9 characters, so may I change the code and just add 9 characters to 'tdentry_str_size' ?
> 
> Address -> td.c line 105

Never hardcode any numeric values: it's a receipt for disaster. Right now, if we wanted the format changed, it's just changing the specific macro.
